# Generated by Django 3.2.8 on 2022-11-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutojeffersonian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
